[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\niveristandadd-ons\custom devices\engine_sim_toolkit_custom_device'

[projects.cd]
path = 'Source\Engine Simulation Toolkit Custom Device.lvproj'

[projects.file_format]
path = 'Source\File Format Classes\FileFormat.lvproj'

[[build.steps]]
name = 'File Format Library'
type = 'lvBuildSpec'
project = '{file_format}'
target = 'My Computer'
build_spec = 'File Formats'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'

[package]
type = 'nipkg'
name = 'engine-simulation-toolkit-custom-device-{veristand_version}'
dev_xml_path = 'Source\Custom Device Engine Simulation Toolkit.xml'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices'

[[release.steps]]
name = 'Master Release'
type = 'githubRelease'
2015_release_branches = ["master",]
2016_release_branches = ["master",]
2017_release_branches = ["master",]
